name: deploy auto

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
      - name: Setup Go environment
        uses: actions/setup-go@v2.1.3
        with:
          go-version: '^1.16.2'

      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: build iotex-analyser-api
        run: make
      - name: print env
        run: |
          echo ${{ secrets.SCOUT_HOST }}, ${{ secrets.SCOUT_USER }}, ${{ secrets.SCOUT_PORT }}
      - name: ssh scp ssh pipelines
        uses: cross-the-world/ssh-scp-ssh-pipelines@latest
        env:
          WELCOME: "ssh scp ssh pipelines"
          LASTSSH: "Doing something after copying"
        with:
          host: ${{ secrets.SCOUT_HOST }}
          user: ${{ secrets.SCOUT_USER }}
          key: ${{ secrets.SCOUT_KEY }}
          port: ${{ secrets.SCOUT_PORT }}
          connect_timeout: 10s
          first_ssh: |
            mv /home/ubuntu/iotex-analyser-api/iotex-analyser-api{,_$(date \+%F)}
            echo $WELCOME
          scp: |
            './iotex-analyser-api' => /home/ubuntu/iotex-analyser-api/
          last_ssh: |
            sudo supervisorctl restart analyser-api
            #sudo supervisorctl restart analyser-api_testnet
